build: 397e226edb9c55d49e67f86ad7e6431164b16405

diff --git a/.github/workflows/reusable.yml b/.github/workflows/reusable.yml
--- a/.github/workflows/reusable.yml
+++ b/.github/workflows/reusable.yml
@@ -10,10 +10,13 @@ on:
         type: string
 
 jobs:
-  build:
+  distribute_job:
     if: (contains(github.event.head_commit.message, 'build') && !contains(github.event.head_commit.message, 'skip ci'))
-    name: Build
+    name: distribute-job
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        exchange: ['bingx', 'bitget', 'bitmart', 'bitmex', 'bybit', 'coinex', 'cryptocom', 'gate', 'hashkey', 'htx', 'hyperliquid', 'kucoin', 'kucoinfutures', 'mexc', 'okx', 'woo', 'woofipro']
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -22,7 +25,7 @@ jobs:
           persist-credentials: false
 
       - name: Push to another repo (approach A)
-        if: (contains(github.event.head_commit.message, 'BUILD_A'))
+        if: (!contains(github.event.head_commit.message, 'BUILD_WITH_REMOTE'))
         run: |
           TEMP_DIR=$(mktemp -d)
           TEMP_DIR_GIT="$TEMP_DIR/python-${{ inputs.exchange_name }}"
@@ -35,15 +38,15 @@ jobs:
           git commit -m "build: ${{ github.sha }}"
           git push origin main --force
   
-      - name: Push to another repo (approach B)
-        if: (!contains(github.event.head_commit.message, 'BUILD_B'))
-        run: |
-          git config user.name github-actions
-          git config user.email github-actions@github.com
-          git remote add prod https://x-access-token:${{ secrets.API_TOKEN_FOR_CCXT_SINGLE_EXCHANGES }}@github.com/ccxt/python-${{ inputs.exchange_name }}.git
-          git config pull.rebase false
-          git fetch --unshallow origin
-          git pull --allow-unrelated-histories prod main || echo "Git pull failed"
-          git push prod main --force
+      # - name: Push to another repo (approach B)
+      #   if: (contains(github.event.head_commit.message, 'BUILD_WITH_REMOTE'))
+      #   run: |
+      #     git config user.name github-actions
+      #     git config user.email github-actions@github.com
+      #     git remote add prod https://x-access-token:${{ secrets.API_TOKEN_FOR_CCXT_SINGLE_EXCHANGES }}@github.com/ccxt/python-${{ inputs.exchange_name }}.git
+      #     git config pull.rebase false
+      #     git fetch --unshallow origin
+      #     git pull --allow-unrelated-histories prod main || echo "Git pull failed"
+      #     git push prod main --force
 
           
